version: '3.3'

volumes:
    pg_data:
    static:
    media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    image: zaritskiyaa/foodgram_frontend
    env_file: .env
    volumes:
      - ./frontend/:/app/result_build/
  backend:
    depends_on:
      - db
    image:  zaritskiyaa/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  nginx:
    image:  zaritskiyaa/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - static:/statifiles/
      - media:/media
