# Generated by Django 3.2.16 on 2023-11-13 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import foodgram.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'value',
                    models.SmallIntegerField(verbose_name='Колличество'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Укажите название',
                        max_length=200,
                        unique=True,
                        verbose_name='Название',
                    ),
                ),
                (
                    'measurement_unit',
                    models.CharField(
                        help_text='Укажите единицу измерения',
                        max_length=200,
                        verbose_name='Единица измерения',
                    ),
                ),
                (
                    'amount',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='foodgram.amount',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Ingridients',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Укажите название',
                        max_length=200,
                        unique=True,
                        verbose_name='Название',
                    ),
                ),
                (
                    'color',
                    models.CharField(
                        help_text='Укажите цвет',
                        max_length=7,
                        null=True,
                        unique=True,
                        verbose_name='Цвет',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='Укажите слаг, поле должно быть уникальным',
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name='Слаг',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Укажите название',
                        max_length=200,
                        unique=True,
                        verbose_name='Название',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        help_text='Добавьте фотографию рецепта',
                        upload_to='',
                        verbose_name='Фотография',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        help_text='Опишите рецепт',
                        verbose_name='Описание рецепта',
                    ),
                ),
                (
                    'coocking_time',
                    models.PositiveSmallIntegerField(
                        help_text='Укажите время приготовления',
                        validators=[foodgram.validators.validate_time],
                        verbose_name='Время приготовления',
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recipe',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Автор рецепта',
                    ),
                ),
                (
                    'ingridients',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='recipe',
                        to='foodgram.ingridient',
                        verbose_name='Ингридиенты',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='recipe',
                        to='foodgram.tag',
                        verbose_name='Тэг',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Recipes',
                'default_related_name': 'recipe',
            },
        ),
    ]
