# Generated by Django 3.2.16 on 2023-11-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
