# Generated by Django 3.2.16 on 2023-11-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('foodgram', '0003_remove_ingridient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=models.CharField(
                help_text='Укажите название',
                max_length=200,
                verbose_name='Название',
            ),
        ),
    ]
