# Generated by Django 3.2.16 on 2023-11-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('foodgram', '0004_alter_ingridient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngridients',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'amount',
                    models.SmallIntegerField(verbose_name='Колличество'),
                ),
                (
                    'ingridient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='foodgram.ingridient',
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='recipeingridients',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='foodgram.recipe',
            ),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingridients',
            field=models.ManyToManyField(
                related_name='recipe',
                through='foodgram.RecipeIngridients',
                to='foodgram.Ingridient',
                verbose_name='Ингридиенты',
            ),
        ),
    ]
