# Generated by Django 3.2.16 on 2023-11-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('foodgram', '0007_auto_20231115_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridients',
            name='ingridient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='foodgram.ingridient',
            ),
        ),
        migrations.AlterField(
            model_name='recipeingridients',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='foodgram.recipe',
            ),
        ),
    ]
