# Generated by Django 3.2.16 on 2023-11-15 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foodgram', '0010_auto_20231115_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
