# Generated by Django 3.2.16 on 2023-11-15 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foodgram', '0012_rename_coocking_time_recipe_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridients',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipeingridients',
            old_name='ingridient',
            new_name='ingredients',
        ),
    ]
